apiVersion: v1
kind: ConfigMap
metadata:
  name: odk-backend-config
data:
  config.json: |
    {
        "default": {
            "database": {
                "host": {{ .Values.app.container.env.dbHost | quote }},
                "user": {{ .Values.app.container.env.dbUser | quote }},
                "password": {{ .Values.app.container.env.dbPassword | quote }},
                "database": {{ .Values.app.container.env.dbName | quote }}
            },
            "xlsform": {
                "host": "pyxform",
                "port": 80
            },
            "enketo": {
                "url": "http://enketo:8005/-",
                "apiKey": {{ .Values.app.container.env.enketoApiKey | quote }}
            },
            "env": {
                "domain": "https://{{ .Values.networking.ingress.host }}",
                "sysadminAccount": {{ .Values.app.container.env.sysAdminEmail | quote }}
            }
        }
    }
