apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.enketo.configSecretName }} 
type: Opaque
data:
  enketo-secret: |-
    {{ randAlphaNum 64 | b64enc | nindent 4 }}
  enketo-less-secret: |-
    {{ randAlphaNum 32 | b64enc | nindent 4 }}
  enketo-api-key: |-
    {{ .Values.app.container.env.enketoApiKey | b64enc | nindent 4 }}