apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.enketo.configSecretName }}
data:
  config.json: {{ .Values.enketoSettingsConfig | quote }}
  default-config.json: {{ .Values.enketoSettingsConfig | quote }}
  express.js: {{ .Files.Get "express.js" | quote }}