apiVersion: apps/v1
kind: Deployment
metadata:
  name: odk-pyxform
  labels:
    app: odk-pyxform
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: odk-pyxform
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: odk-pyxform
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: odk-pyxform
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pyxform.image.registry }}/{{ .Values.pyxform.image.repository }}:{{ .Values.pyxform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pyxform.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontendport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}