apiVersion: apps/v1
kind: Deployment
metadata:
  name: odk-central-frontend
  labels:
    app: odk-frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: odk-frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: odk-frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: odk-central-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontendport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        
          env:
            - name: SSL_TYPE
              value: "upstream"

            - name: DOMAIN
              value: {{ .Values.networking.frontend.ingress.host }}

            - name: SYSADMIN_EMAIL
              value: {{ .Values.app.container.env.sysAdminEmail | quote }}
            
            - name: CERTBOT_EMAIL
              value: {{ .Values.app.container.env.sysAdminEmail | quote }}