apiVersion: v1
kind: Service
metadata:
  name: odk-central-service
  labels:
    app: odk-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.frontendport }}
      targetPort: {{ .Values.service.frontendport }}
      protocol: TCP
      name: http

  selector:
    app: odk-frontend
