# Default values for odk-central.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  container:
    imagePullPolicy: "Always"
    port: 8080
    env:
      googleApplicationCredentialsSecret:
        name: "odk-service-account"
        filePath: "/secrets/gcp/key.json"
        mountPath: "/secrets/gcp"

image:
  repository: docker.io/openg2p/odk-central-backend
  pullPolicy: Always
  tag: v2023.1.0

odkweb:
  image:
    repository: docker.io/openg2p/odk-central-frontend
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: v2023.1.0

enketo:
  configfilepath: "/srv/src/enketo_express/config/config.json"
  configmountpath: "/srv/src/enketo_express/config"
  configSecretName: "enketo-config-secrets"
  container:
    port: 8005
  image:
    repository: enketo/enketo-express
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 6.1.0

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: "kong"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

sslType: upstream
nginxDomain: "_"
