name: ODK Central Deployment

on: [push]

env:
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  APP_NAME: ${{ secrets.APP_NAME }}
  SYSADMIN_EMAIL: ${{ secrets.SYSADMIN_EMAIL }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_SSL: ${{ secrets.DB_SSL }}
  DB_INSTANCE_CONNECTION_NAME: ${{ secrets.DB_INSTANCE_CONNECTION_NAME }}
  FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
  FRONTEND_APP_DOMAIN: ${{ secrets.FRONTEND_APP_DOMAIN }}
  BACKEND_APP_DOMAIN: ${{ secrets.BACKEND_APP_DOMAIN }}
  ENKETO_API_KEY: ${{ secrets.ENKETO_API_KEY }}
  ENKETO_DOMAIN: ${{ secrets.ENKETO_DOMAIN }}

jobs:
  deploy_to_testing:
    name: Deploy testing server to google kubernetes engine
    strategy:
      matrix:
        environment: [test, sil-testing]
    
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy to Google Kubernetes engine
        shell: bash
        run: cd deploy/ && cat deploy.sh && sh deploy.sh

  deploy_to_prod:
    name: Deploy prod server to google kubernetes engine
    strategy:
      matrix:
        environment: [mch-prod, sil-prod]
    
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy to Google Kubernetes engine
        shell: bash
        run: cd deploy/ && cat deploy.sh && sh deploy.sh